server:
  port: 8282
spring:
  application:
    name: swag-gateway
  #  cloud:
  #    gateway:
  #        discovery:
  #          locator:
  #            enabled: true
  #            lower-case-service-id: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
#      routes:
#        - id: ms-customer
#          uri: lb://ms-customer
#          predicates:
#            - Path=/ms-customer/**
#          filters:
#            - RewritePath=/ms-customer/(?<path>.*), /$\{path}
#        - id: ms-account
#          uri: lb://ms-account
#          predicates:
#            - Path=/ms-account/**
#          filters:
#            - RewritePath=/ms-account/(?<path>.*), /$\{path}
#        - id: currency-converter
#          uri: lb://currency-converter
#          predicates:
#            - Path=/currency-converter/**
#          filters:
#            - RewritePath=/currency-converter/(?<path>.*), /$\{path}
      routes:
        - id: swag-home
          uri: lb://swag-home
          predicates:
            - Path=/swag-home/**
          filters:
            - RewritePath=/swag-home/(?<path>.*), /$\{path}
        - id: swag-artist
          uri: lb://swag-artist
          predicates:
            - Path=/swag-artist/**
          filters:
            - RewritePath=/swag-artist/(?<path>.*), /$\{path}
        - id: swag-profile
          uri: lb://swag-profile
          predicates:
            - Path=/swag-profile/**
          filters:
            - RewritePath=/swag-profile/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://swag-discovery:8703/eureka/
#      defaultZone: http://localhost:8703/eureka/
